### ISSUE TITLE
What is the meanings of these notions? I am really confused

### ISSUE THREAD

**Issue by theodoruszq** [ehsanik/SeGAN#7]
In your paper, Equation 1
![image](https://user-images.githubusercontent.com/21001467/94270526-c124f200-ff72-11ea-9305-5988a0a74072.png)
The input to the inpainting network:

My understand: 
I -> Image
V -> Visible mask of the object
O -> Amodal/Full mask of the object
J -> All one mask

Am I right, if that is the case, the composed image would be like this:
![image](https://user-images.githubusercontent.com/21001467/94270623-efa2cd00-ff72-11ea-84b3-12420ff5f419.png)

Are you sure about that?

**Comment by theodoruszq** [comment]
Or something like this and it looks really weird, please confirm there exists no error in your equation!
![image](https://user-images.githubusercontent.com/21001467/94271002-91c2b500-ff73-11ea-94fb-9bb20f011346.png)

**Comment by ehsanik** [comment]
Hi and thanks for reaching out. There is no error in the equation.

So V, O and J are all binary masks and (V), (O-V) and (J-O-V) are mutually exclusive masks, therefore, this function should not distort the colors of your image. I'm guessing you are doing something wrong with RGB-ordering.

The image you have should be similar to your original image for the visible part, all red pixels for invisible parts and blue pixels for the background. Looking at your images, I'm pretty sure your channel ordering is not correct. Also you need to double-check your masks to make sure they are correct.

Unfortunately, I don't know what your problem is or what this figure is representing. If you want you can email me and give me more context and I will try to help if I can :)
